In [2]:
def test(a,b=10,c=100):
    print(a)
    print(b)
    return
    print(c)

print(test(b=12,a=22,c=33))

22
12
None


In [2]:
[a,b] = [2,3]
(c,d) = (101,202)
print(a,b,c,d)
print(type(a),type(b),type(c),type(d))


2 3 101 202
<class 'int'> <class 'int'> <class 'int'> <class 'int'>


파이썬에서 함수의 매개변수에서 함수를 호출할때 왜 괄호를 생략할수 있을까?
-> 자바와 다르게 파이썬에서 함수는 읿급객체 취급을 받는다

In [5]:
def doncallme(func):
    for i in range(4):
        func()

def print_hello():
    print("Hello")

doncallme(print_hello)
print(type(print_hello))
type(print_hello)

Hello
Hello
Hello
Hello
<class 'function'>


function

In [ ]:
def power(item):
    return item*item
list_input = [1,2,3,4,5]
ark = 3

In [8]:
a = 1;  b = 2; print(a + b)


3


In [18]:
def power1(item):
    return item*item
list_input1 = [1,2,3,4,5]
list_input2 = [1,2,3,4,5]

output = map(power1, list_input1,list_input2)
print(output)

[1, 2, 3, 4, 5]

In [4]:
mylam = lambda x : x**2
mylam(2)

with open("basic.txt","r") as file:
    content = file.read()

print(content)


FileNotFoundError: [Errno 2] No such file or directory: 'basic.txt'

In [5]:
def myworld():
    global ark
    ark = "lee"

#myworld()
print(ark)


lee


In [7]:
def myworld():
    global asf
    asf = "lee"

myworld()
print(asf)


lee


In [21]:
import random

hanguls = list("가나다라마바사아자차카타파하")
print(hanguls)
name = random.choice(hanguls) + random.choice(hanguls)
print(name)



['가', '나', '다', '라', '마', '바', '사', '아', '자', '차', '카', '타', '파', '하']
가아


for 반복자 in 반복할 수 있는 것
여기서 반복 수 있는것을 이터러블이라고함 (Ex list 나 range)
이터러블 중에서 next() 함수를 적용해 하나하나 꺼낼 수 있는 요소를 이터레이터라고 한다.

In [6]:
def test():
    print("A 지점 통과")
    yield 1
    print("B pass")
    yield 2
    print("C pass")
    yield 3

output = test()
print(output)
a = next(output)
print(a)

<generator object test at 0x107346e00>
A 지점 통과
1


In [3]:

try :
    user_input_a = int(input("enter digit> "))
    print(user_input_a)
except :
    print("error")


32


In [1]:
number = input("enter number> ")
ark = int (number)

if ark > 0:
    print(ark)
    raise NotImplementedError
else:
    print("error")
    raise NotImplementedError

2


NotImplementedError: 

In [1]:
try:
    ark = int(input("enter digit> "))

except Exception as e:
    print(type(e))
    print(e)



In [1]:
import random

print(random.shuffle([1,2,3,4,5]))

None


In [2]:
import sys


print(sys.copyright)

Copyright (c) 2001-2023 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved.


In [3]:
import os

print(os.name)


posix


In [11]:
import datetime

now = datetime.datetime.now()
print(now)

td = datetime.timedelta(
    weeks=1,
    days = 1)
print(td)

2025-03-14 21:02:56.261273
8 days, 0:00:00


In [14]:
import ssl
from urllib import request

# SSL 인증서 검증을 하지 않는 컨텍스트 생성
context = ssl._create_unverified_context()

target = request.urlopen("https://www.google.co.kr/?hl=ko", context=context)
print(target.read())

b'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="ko"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="ClsQ-wcQugjuPBepWjakTg">(function(){var _g={kEI:\'Ex3UZ9OSJqmIvr0Pg8yU8A4\',kEXPI:\'0,202791,3497541,617,435,538661,2872,2891,89155,201864,142932,247319,42725,5230280,11449,25,5988575,2846318,78,3,2,3,2,3,1,23933875,4043710,25228681,112121,26147,8181,5936,65162,54,6702,23879,9139,4599,328,6225,1116,33194,3511,26343,1347,13702,8213,871,6551,12129,2392,6781,33,9041,12505,2,5160,771,9901,21339,2986,5354,41,13639,1,4930,1811,4106,352,7384,4956,6131,409,3118,3,3700,937,1212,4614,5112,662,4309,8754,3588,3352,5819,1789,927,4,3788,10121,49,1635,3254,8,458,4023,1963,2503,1254,56,1023,1,576,255,221,1,2056,2256,75,1471,2,1734,569,2367,940,286,2,597,327,967,843,2201,812,1842,354,656,611,3143,808,459,6,90,7,111,1229,1

In [2]:
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"




In [8]:
from math import sin,cos,tan

print(sin(1))
print(cos(1))
print(tan(3.14159265358979/2))

0.8414709848078965
0.5403023058681398
618986325617924.2


In [19]:
import ssl
from urllib import request

context = ssl._create_unverified_context()


target = request.urlopen("https://www.google.co.kr/",context=context)
output = target.read()
text = output.decode('euc-kr')

print(output)
print("-------------------------------------------------------------")
print(text)



b'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="ko"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="pnPLXMBwaQN67-cetDIIkg">(function(){var _g={kEI:\'A33WZ_4J3dPV7w_UsbSgDg\',kEXPI:\'0,202791,3497528,630,435,538661,2872,2891,73050,16105,344796,238458,51586,5241722,32,8834893,79,3,3,4,2,2,4,27977580,25228681,112121,26147,8181,5936,57124,8037,6757,23879,9139,4599,328,6225,1117,9301,13948,9945,29854,1346,13702,8213,7422,12129,9173,33,9041,17667,10672,21339,2988,5352,41,13639,1,6741,4105,353,7384,4956,6540,69,3049,3,3699,928,1219,4617,5773,4311,12341,143,8155,2662,4719,7583,2184,403,1635,3254,8,458,2531,35,2266,6,1148,2115,388,324,930,55,776,251,1,828,221,1,4312,74,3208,569,2250,117,1226,599,43,7,1244,657,3199,1842,354,532,2,124,609,3143,808,459,6,90,7,1340,1942,5,1143,160,742,2,413,1761,662,2422,245,141,34

In [21]:
print(1,2,3,4,5)
print(1,2,3,4,5,sep="\t")
ark = 1
ark ="alstn"
print(ark)


1 2 3 4 5
1	2	3	4	5
alstn


In [23]:
ark = 1 +\
    2
print(ark)

3


In [25]:
class Student:
    pass

student = Student()

students = [
    Student(),
    Student(),
    Student(),
    Student(),
    Student(),
    Student()
]

print(students)
print(students[0])
print(student)

[<__main__.Student object at 0x10953b1d0>, <__main__.Student object at 0x109530490>, <__main__.Student object at 0x109531a10>, <__main__.Student object at 0x1095312d0>, <__main__.Student object at 0x1095301d0>, <__main__.Student object at 0x109533610>]


In [26]:
import __main__

class Student:

    def __init__(self, name, age):
        self.name = name
        self.age = age

students = [Student("smrma",23),Student("smroq",33)]
print(students)
stu = Student("smrma",23)
print(stu)
print(type(stu))
stu.grade = "c"

print(stu.grade)
stu.grade = "d"
print(stu.grade)
print(type(stu.grade))
print(isinstance(stu.grade,str))
print(isinstance(stu,__main__.Student))
print(isinstance(stu,Student))
ark = 3
print(type(ark))


[<__main__.Student object at 0x105e6e590>, <__main__.Student object at 0x105e6e510>]
<class '__main__.Student'>
c
d
<class 'str'>
True
True
True
<class 'int'>


In [28]:
class Lilgay:
    count = 0

    def __init__(self):
        Lilgay.count +=1

ark1 = Lilgay()
ark2 = Lilgay()
print(ark2.count)
ark2.count = 5
print(ark1.count)

2
2


In [3]:
arr = [0]*12
print(arr)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [6]:
arr1 = [[1]*3]*6
print(arr1)
arr1[0][0] = 2
print(arr1)

[[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[2, 1, 1], [2, 1, 1], [2, 1, 1], [2, 1, 1], [2, 1, 1], [2, 1, 1]]


In [7]:
maruta = [[0]*6 for _ in range(6)]
print(maruta)

maruta[0][0] = 523
print(maruta)
print(maruta[0])

[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]
[[523, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]
[523, 0, 0, 0, 0, 0]


In [2]:
import numpy as np

sample = np.array([[1,2,3],[4,5,6]])
print(sample)

for row in sample:
    print(row)

print("end")


[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
end


In [14]:
import numpy as np

sample = np.array([[1,2,3],[4,5,6]])
print(sample)
sample = sample.flatten()
ark = sample[np.array([0,1])]
print(ark)
print(type(ark))
pos = sample>3
print(pos)
print(type(pos))
sample[sample>3]

[[1 2 3]
 [4 5 6]]
[1 2]
<class 'numpy.ndarray'>
[False False False  True  True  True]
<class 'numpy.ndarray'>


array([4, 5, 6])